version: "3.9"
services:
  app:
    build:
      context: "."
      dockerfile: ./Dockerfile-node
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ../app:/app
    working_dir: /app
    environment:
      - TZ=${TZ}
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.30.0.5

  db:
    build:
      context: "."
      dockerfile: ./Dockerfile-mysql
    volumes:
      - db:/var/lib/mysql
      - db-log:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    networks:
      app_net:
        ipv4_address: 172.30.0.4

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

volumes:
  db: {}
  db-log: {}